# Generated by Django 3.0.6 on 2020-07-03 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FThrottle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 3, 14, 48, 36, 767936)),
        ),
    ]
