# Generated by Django 3.0.6 on 2020-07-03 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FThrottle', '0005_auto_20200703_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 3, 16, 4, 6, 377194)),
        ),
    ]
